tasks:
  - init: /workspace/rustlings/install.sh
    command: /workspace/.cargo/bin/rustlings watch

vscode:
  extensions:
    - rust-lang.rust@0.7.8:CvNqMTgDdt3UXt+6BCDTVg==
    - vscodevim.vim@1.18.5:mvmr2A2vpFZRzLfyxtznHw==